#!/usr/bin/env node
/**
 * Drift check for the native Playwright agents.
 *
 * `.claude/agents/playwright-test-{planner,generator,healer}.md`, `.mcp.json` and
 * `specs/README.md` are generated by `npx playwright init-agents` and committed
 * pristine, so they stay in sync with upstream Playwright. This regenerates them and
 * fails if the result differs from what is committed — the fork can never silently
 * diverge (and lose the `browser_verify_*` grounding loop) the way a hand-edited copy
 * did before.
 *
 * Governance lives in `.claude/CLAUDE.md` and `AGENTS.md`, NOT in the agent files, so a
 * change to how the agents are governed never trips this check. If this check fails,
 * upstream changed: review the regenerated files and commit them.
 *
 * Dep-free (Node builtins + the Playwright CLI already in devDependencies).
 */
const { execFileSync } = require('child_process');

// The files init-agents owns and that we commit. `.features-gen/` is gitignored, so its
// regenerated seed is ignored here automatically.
const OWNED = [
  '.claude/agents/playwright-test-generator.md',
  '.claude/agents/playwright-test-healer.md',
  '.claude/agents/playwright-test-planner.md',
  '.mcp.json',
  'specs/README.md',
];

try {
  execFileSync('npx', ['playwright', 'init-agents', '--loop=claude', '--project=bdd:chromium'], { stdio: 'inherit' });
} catch (e) {
  console.error(`\nagents:sync: could not regenerate agents (${e.message}).`);
  process.exit(2);
}

const drifted = execFileSync('git', ['diff', '--name-only', '--', ...OWNED], { encoding: 'utf8' })
  .split('\n')
  .filter(Boolean);

if (drifted.length) {
  console.error('\nagents:sync: the native Playwright agents have drifted from upstream:');
  for (const f of drifted) console.error(`  ✗ ${f}`);
  console.error('\nUpstream changed. Review the regenerated files and commit them.');
  console.error('Governance belongs in .claude/CLAUDE.md, not in the agent definitions.');
  process.exit(1);
}

console.log('agents:sync: native Playwright agents are in sync with upstream ✓');
