#!/usr/bin/env node
/**
 * Documentation drift check.
 *
 * Documentation rots silently: a script is renamed, a file is deleted, and the guide
 * that references it keeps saying the old thing. That is worse here than in most
 * projects, because these documents are also what AI agents read before generating
 * code — a stale instruction becomes a stale test.
 *
 * Two checks, both cheap and both deterministic:
 *
 *   1. Every `npm run <script>` mentioned in a Markdown file exists in package.json.
 *   2. Every repo-relative link and inline path in a Markdown file resolves on disk.
 *
 * Dep-free so it runs in CI without an install step beyond npm ci.
 * Exits 1 and lists every problem; exits 0 silently when clean.
 *
 * Usage: node scripts/check-docs.js
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');

/**
 * Paths that appear in guides as *examples of what you would write*, not as claims
 * that this repository contains them. A teaching guide showing `components/Pagination.ts`
 * is illustrating a pattern; flagging it would train people to ignore this check.
 */
const ILLUSTRATIVE = [
  'tmp/', // scratch the remote healer creates at run time
  'cypress/', // the *source* project in a migration guide, deliberately absent here
  'components/', // suggested component-object layout
  'pages/components/',
  'pages/MyFeaturePage.ts',
  'utils/api-client.ts',
  'test-data/api-responses/',
  'tests/__snapshots__/', // generated by Playwright on first run
  'tests/api/', // documented as "add these for your app"
  'tests/visual/',
  'tests/performance/',
  'features/auth.feature',
  '.claude/',
  '.cursorrules',
];

/** Documented as things the reader creates or the suite generates, not things we ship. */
const EXPECTED_ABSENT = new Set([
  '.env', // created by the reader from .env.example
  'test-data/.auth/user.json', // produced by the auth seed
]);

const isIllustrative = (p) => ILLUSTRATIVE.some((i) => (i.endsWith('/') ? p.startsWith(i) : p === i));

/**
 * Only tracked files. Walking the filesystem would pick up generated reports and other
 * ignored artefacts, which are not documentation and are frequently stale by design.
 */
function markdownFiles() {
  return require('child_process')
    .execSync('git ls-files "*.md"', { cwd: ROOT, encoding: 'utf8' })
    .split('\n')
    .filter(Boolean)
    .map((f) => path.join(ROOT, f));
}

/** Strip fenced code blocks so example snippets do not produce false positives. */
function stripFences(text) {
  return text.replace(/```[\s\S]*?```/g, (block) => block.replace(/[^\n]/g, ' '));
}

function lineOf(text, index) {
  return text.slice(0, index).split('\n').length;
}

const problems = [];
const scripts = new Set(
  Object.keys(JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8')).scripts || {}),
);

for (const file of markdownFiles()) {
  const raw = fs.readFileSync(file, 'utf8');
  const text = stripFences(raw);
  const rel = path.relative(ROOT, file);

  // ── 1. npm run <script> ───────────────────────────────────────────────────
  for (const m of text.matchAll(/`npm run ([a-z0-9:_-]+)`/gi)) {
    if (!scripts.has(m[1])) {
      problems.push(`${rel}:${lineOf(text, m.index)} — npm run ${m[1]} is not a script in package.json`);
    }
  }

  // ── 2. repo-relative links and inline paths ───────────────────────────────
  const candidates = new Set();

  // Markdown links: [text](./path) or [text](path/to/file.md)
  for (const m of text.matchAll(/\]\(([^)]+)\)/g)) candidates.add(m[1]);
  // Inline code that looks like a repo path: `fixtures/index.ts`, `docs/ARCHITECTURE.md`
  for (const m of text.matchAll(/`([a-zA-Z0-9._-]+\/[a-zA-Z0-9._/-]+)`/g)) candidates.add(m[1]);

  for (const target of candidates) {
    const clean = target.split('#')[0].split('?')[0].trim();
    if (!clean) continue;
    if (/^(https?:|mailto:|#)/.test(clean)) continue;
    if (clean.includes('<') || clean.includes('*')) continue; // placeholders and globs
    const normalised = clean.replace(/^\.\//, '');
    if (EXPECTED_ABSENT.has(normalised) || isIllustrative(normalised)) continue;

    // Resolve relative to the document, then fall back to the repo root, since docs
    // reference both ways.
    const fromDoc = path.resolve(path.dirname(file), clean);
    const fromRoot = path.resolve(ROOT, clean.replace(/^\.\//, ''));
    if (fs.existsSync(fromDoc) || fs.existsSync(fromRoot)) continue;

    // Only complain about things that look like real repo paths, so prose such as
    // `getByRole/getByLabel` is not mistaken for a directory.
    const looksLikePath = /\.[a-z0-9]+$/i.test(clean) || clean.endsWith('/');
    if (!looksLikePath) continue;

    const idx = text.indexOf(target);
    problems.push(`${rel}:${idx >= 0 ? lineOf(text, idx) : '?'} — ${clean} does not exist`);
  }
}

if (problems.length > 0) {
  console.error(`\n✖ ${problems.length} documentation reference${problems.length === 1 ? '' : 's'} did not resolve:\n`);
  for (const p of problems.sort()) console.error(`  ${p}`);
  console.error('\n  Fix the reference, or remove it. Docs that lie are worse than docs that are missing.\n');
  process.exit(1);
}

console.log('✓ docs check: every npm script and repo path referenced in Markdown resolves');
